=== SavvasRaptis/Jets-Reformation/irfu-matlab/irfu-matlab-master/mission/cluster/caa/caa-control/regions.dtd
<!-- 
Regions DTD

$Id$
 -->

<!ELEMENT regions (title,region+)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT region (#PCDATA)>
			<!ATTLIST region start NMTOKEN #REQUIRED>
			<!ATTLIST region desc ( mp|sh|bs|sw|psh|psp|az|lo|cusp|nodata|undef ) #REQUIRED>

=== SavvasRaptis/Jets-Reformation/irfu-matlab/irfu-matlab-master/mission/cluster/caa/caa-control/regions-2001-06.xml
<?xml version="1.0"?>
<!DOCTYPE regions SYSTEM "https://www.space.irfu.se/regions.dtd">

<!--
List of regions crossed by Cluster for 2001-06

$Id$
-->
<regions>
<title>2001-06</title>
<region start="2001-06-01T00:00:00.000Z" desc="nodata"/>
<region start="2001-06-01T04:57:04.000Z" desc="undef"/>
<region start="2001-06-01T09:00:00.000Z" desc="cusp"/>
<region start="2001-06-01T13:05:00.000Z" desc="mp"/>
<region start="2001-06-01T13:25:00.000Z" desc="sh"/>
<region start="2001-06-01T21:10:00.000Z" desc="bs"/>
<region start="2001-06-01T21:28:00.000Z" desc="sw"/>
<region start="2001-06-01T21:35:00.000Z" desc="bs"/>
<region start="2001-06-01T21:46:00.000Z" desc="sw"/>
<region start="2001-06-01T21:53:00.000Z" desc="bs"/>
<region start="2001-06-01T21:57:00.000Z" desc="sh"/>
<region start="2001-06-01T22:11:00.000Z" desc="bs"/>
<region start="2001-06-01T22:19:00.000Z" desc="sh"/>
<region start="2001-06-01T23:49:00.000Z" desc="bs"/>
<region start="2001-06-02T00:43:00.000Z" desc="sw"/>
<region start="2001-06-02T00:51:00.000Z" desc="bs"/>
<region start="2001-06-02T00:58:00.000Z" desc="sh"/>
<region start="2001-06-02T03:10:00.000Z" desc="bs"/>
<region start="2001-06-02T04:00:00.000Z" desc="sw"/>
<region start="2001-06-02T04:40:00.000Z" desc="bs"/>
<region start="2001-06-02T04:55:00.000Z" desc="sh"/>
<region start="2001-06-02T09:47:00.000Z" desc="bs"/>
<region start="2001-06-02T10:16:00.000Z" desc="sw"/>
<region start="2001-06-02T10:29:00.000Z" desc="bs"/>
<region start="2001-06-02T10:49:00.000Z" desc="sw"/>
<region start="2001-06-02T18:10:00.000Z" desc="mp"/>
<region start="2001-06-02T20:53:55.000Z" desc="nodata"/>
<region start="2001-06-03T13:24:36.000Z" desc="undef"/>
<region start="2001-06-03T19:49:27.000Z" desc="nodata"/>
<region start="2001-06-03T22:32:25.000Z" desc="undef"/>
<region start="2001-06-04T11:53:01.000Z" desc="nodata"/>
<region start="2001-06-04T14:07:35.000Z" desc="sh"/>
<region start="2001-06-04T20:50:00.000Z" desc="mp"/>
<region start="2001-06-04T21:30:00.000Z" desc="sh"/>
<region start="2001-06-05T00:45:00.000Z" desc="mp"/>
<region start="2001-06-05T07:40:00.000Z" desc="psh"/>
<region start="2001-06-05T16:50:00.000Z" desc="lo"/>
<region start="2001-06-06T12:25:43.000Z" desc="nodata"/>
<region start="2001-06-07T00:58:24.000Z" desc="undef"/>
<region start="2001-06-07T02:00:00.000Z" desc="mp"/>
<region start="2001-06-07T02:34:00.000Z" desc="sh"/>
<region start="2001-06-07T07:15:00.000Z" desc="mp"/>
<region start="2001-06-07T09:55:34.000Z" desc="nodata"/>
<region start="2001-06-07T13:37:04.000Z" desc="psh"/>
<region start="2001-06-07T15:09:00.000Z" desc="mp"/>
<region start="2001-06-07T15:15:00.000Z" desc="sh"/>
<region start="2001-06-07T15:19:00.000Z" desc="mp"/>
<region start="2001-06-07T15:21:00.000Z" desc="psh"/>
<region start="2001-06-07T16:20:00.000Z" desc="mp"/>
<region start="2001-06-07T21:34:54.000Z" desc="nodata"/>
<region start="2001-06-08T02:48:32.000Z" desc="lo"/>
<region start="2001-06-08T11:48:14.000Z" desc="nodata"/>
<region start="2001-06-08T12:12:36.000Z" desc="lo"/>
<region start="2001-06-08T18:03:00.000Z" desc="mp"/>
<region start="2001-06-08T18:25:00.000Z" desc="sh"/>
<region start="2001-06-08T19:44:54.000Z" desc="nodata"/>
<region start="2001-06-09T00:00:01.000Z" desc="sh"/>
<region start="2001-06-09T15:58:56.000Z" desc="nodata"/>
<region start="2001-06-09T21:57:05.000Z" desc="sh"/>
<region start="2001-06-10T02:07:00.000Z" desc="mp"/>
<region start="2001-06-10T02:43:54.000Z" desc="nodata"/>
<region start="2001-06-10T04:11:13.000Z" desc="undef"/>
<region start="2001-06-10T04:29:10.000Z" desc="nodata"/>
<region start="2001-06-10T04:52:32.000Z" desc="undef"/>
<region start="2001-06-10T05:07:33.000Z" desc="nodata"/>
<region start="2001-06-10T15:40:41.000Z" desc="undef"/>
<region start="2001-06-10T22:30:00.000Z" desc="cusp"/>
<region start="2001-06-11T01:25:00.000Z" desc="mp"/>
<region start="2001-06-11T03:00:00.000Z" desc="sh"/>
<region start="2001-06-11T05:37:00.000Z" desc="mp"/>
<region start="2001-06-11T05:55:00.000Z" desc="lo"/>
<region start="2001-06-11T09:40:00.000Z" desc="mp"/>
<region start="2001-06-11T10:15:00.000Z" desc="sh"/>
<region start="2001-06-11T11:47:35.000Z" desc="nodata"/>
<region start="2001-06-11T16:58:26.000Z" desc="sh"/>
<region start="2001-06-11T20:00:00.000Z" desc="mp"/>
<region start="2001-06-11T20:25:00.000Z" desc="sh"/>
<region start="2001-06-12T00:50:17.999Z" desc="nodata"/>
<region start="2001-06-12T01:17:11.000Z" desc="undef"/>
<region start="2001-06-12T08:40:00.000Z" desc="cusp"/>
<region start="2001-06-12T09:05:00.000Z" desc="psh"/>
<region start="2001-06-12T11:00:00.000Z" desc="cusp"/>
<region start="2001-06-12T16:14:55.000Z" desc="nodata"/>
<region start="2001-06-12T21:03:11.000Z" desc="lo"/>
<region start="2001-06-12T23:20:00.000Z" desc="az"/>
<region start="2001-06-12T00:10:00.000Z" desc="psp"/>
<region start="2001-06-12T02:30:00.000Z" desc="az"/>
<region start="2001-06-12T03:20:00.000Z" desc="lo"/>
<region start="2001-06-13T13:50:00.000Z" desc="psh"/>
<region start="2001-06-13T14:09:52.999Z" desc="nodata"/>
<region start="2001-06-14T00:05:19.000Z" desc="undef"/>
<region start="2001-06-14T10:12:19.000Z" desc="nodata"/>
<region start="2001-06-14T14:27:03.999Z" desc="undef"/>
<region start="2001-06-14T22:24:52.999Z" desc="nodata"/>
<region start="2001-06-15T06:11:46.000Z" desc="undef"/>
<region start="2001-06-15T17:02:22.000Z" desc="nodata"/>
<region start="2001-06-15T18:45:04.000Z" desc="undef"/>
<region start="2001-06-15T20:49:53.000Z" desc="nodata"/>
<region start="2001-06-15T22:29:06.000Z" desc="undef"/>
<region start="2001-06-16T10:56:42.999Z" desc="nodata"/>
<region start="2001-06-16T12:03:57.000Z" desc="sh"/>
<region start="2001-06-16T15:40:00.000Z" desc="mp"/>
<region start="2001-06-16T16:32:00.000Z" desc="sh"/>
<region start="2001-06-16T17:08:00.000Z" desc="mp"/>
<region start="2001-06-16T18:22:44.000Z" desc="nodata"/>
<region start="2001-06-16T23:40:05.000Z" desc="psh"/>
<region start="2001-06-17T03:39:00.000Z" desc="undef"/>
<region start="2001-06-17T07:17:53.000Z" desc="nodata"/>
<region start="2001-06-17T18:53:36.000Z" desc="undef"/>
<region start="2001-06-18T03:00:00.000Z" desc="sh"/>
<region start="2001-06-18T11:38:26.000Z" desc="nodata"/>
<region start="2001-06-19T00:27:57.000Z" desc="undef"/>
<region start="2001-06-19T14:16:55.000Z" desc="nodata"/>
<region start="2001-06-20T01:02:44.000Z" desc="undef"/>
<region start="2001-06-20T11:40:09.000Z" desc="nodata"/>
<region start="2001-06-20T13:18:45.000Z" desc="undef"/>
<region start="2001-06-20T20:10:55.000Z" desc="nodata"/>
<region start="2001-06-20T23:09:28.000Z" desc="undef"/>
<region start="2001-06-21T11:43:02.000Z" desc="nodata"/>
<region start="2001-06-21T15:11:03.000Z" desc="undef"/>
<region start="2001-06-21T22:07:54.999Z" desc="nodata"/>
<region start="2001-06-22T13:36:12.000Z" desc="undef"/>
<region start="2001-06-23T10:47:46.000Z" desc="nodata"/>
<region start="2001-06-23T14:29:29.000Z" desc="undef"/>
<region start="2001-06-24T07:57:06.000Z" desc="nodata"/>
<region start="2001-06-24T21:44:28.000Z" desc="undef"/>
<region start="2001-06-25T14:04:54.000Z" desc="nodata"/>
<region start="2001-06-25T23:29:58.000Z" desc="undef"/>
<region start="2001-06-26T09:14:22.999Z" desc="nodata"/>
<region start="2001-06-27T04:11:29.000Z" desc="undef"/>
<region start="2001-06-27T09:02:17.999Z" desc="nodata"/>
<region start="2001-06-27T09:28:21.000Z" desc="undef"/>
<region start="2001-06-27T14:53:51.000Z" desc="nodata"/>
<region start="2001-06-27T16:40:04.000Z" desc="undef"/>
<region start="2001-06-28T20:05:54.000Z" desc="nodata"/>
<region start="2001-06-29T01:48:01.000Z" desc="undef"/>
<region start="2001-06-29T02:25:58.000Z" desc="nodata"/>
<region start="2001-06-29T02:47:08.000Z" desc="undef"/>
<region start="2001-06-29T05:42:10.000Z" desc="nodata"/>
<region start="2001-06-29T16:19:51.000Z" desc="undef"/>
<region start="2001-07-01T00:00:00.000Z" desc="nodata"/>
</regions>
