=== SavvasRaptis/Jets-Reformation/irfu-matlab/irfu-matlab-master/mission/mms/mms_ns_ops.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xsd:element name="tables">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="event" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="startDate">
								<xsd:simpleType>
									<xsd:restriction base="xsd:dateTime">
										<xsd:minInclusive value="2015-03-13T00:00:00Z"/>
										<xsd:pattern value="\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.{0,1}\d{0,9}Z"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="stopDate">
								<xsd:simpleType>
									<xsd:restriction base="xsd:dateTime">
										<xsd:minInclusive value="2015-03-13T00:00:00Z"/>
										<xsd:pattern value="\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.{0,1}\d{0,9}Z"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="mms1" type="xsd:boolean"/>
							<xsd:element name="mms2" type="xsd:boolean"/>
							<xsd:element name="mms3" type="xsd:boolean"/>
							<xsd:element name="mms4" type="xsd:boolean"/>
							<xsd:element name="problem">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="no_tm"/>
										<xsd:enumeration value="bad_data"/>
										<xsd:enumeration value="no_p1"/>
										<xsd:enumeration value="no_p2"/>
										<xsd:enumeration value="no_p3"/>
										<xsd:enumeration value="no_p4"/>
										<xsd:enumeration value="spec_bias"/>
										<xsd:enumeration value="bad_bias"/>
										<xsd:enumeration value="info"/>
										<xsd:enumeration value="TBD"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="description" type="xsd:string"/>
							<xsd:element name="link" type="xsd:string" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== SavvasRaptis/Jets-Reformation/irfu-matlab/irfu-matlab-master/mission/mms/mms_ns_ops.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mms_ns_ops.xsd">
<!-- The following columns should be specified for each event:
startDate  stopDate  mms1  mms2  mms3  mms4  problem  description  [link]

startDate   = Date and time at the start of the problematic event
stopDate    = Date and time at the end, both startDate and stopDate should
              be provided in format "YYYY-MM-DDThh:mm:ss[.mmmuuunnn]Z" where
              fractional seconds [.mmmuuunnn] are optional.
mms[1-4]    = Boolean indicator if event affects mms spacecraft [1-4].
problem     = Short description of the anomaly (problem code), possible
              values include:
  - no_tm      = No data at all, e.g. lost DSN download.
  - bad_data   = Bad data.
  - bad_bias   = Bad bias on probe(-s).
  - spec_bias  = Special bias was set on probes and/or guards, e.g.
                 commissioning.
  - no_p[1-4]  = No/bad data on probe(-s) [1-4], e.g. probe failure.
  - info       = informational only (no effect on data processing)
  - TBD        = TBD
description = More informative text describing the event.
link        = Optional link to further information.
-->
	<event>
		<startDate>2002-05-30T09:30:10Z</startDate>
		<stopDate>2002-05-30T10:30:10Z</stopDate>
		<mms1>false</mms1>
		<mms2>false</mms2>
		<mms3>true</mms3>
		<mms4>false</mms4>
		<problem>no_tm</problem>
		<description>A minor test problem</description>
	</event>
	<event>
		<startDate>2012-05-30T09:30:10Z</startDate>
		<stopDate>2012-05-30T10:30:10Z</stopDate>
		<mms1>true</mms1>
		<mms2>false</mms2>
		<mms3>true</mms3>
		<mms4>false</mms4>
		<problem>bad_bias</problem>
		<description>A minor test problem 2</description>
	</event>
	<event>
		<startDate>2012-13-30T09:30:10Z</startDate>
		<stopDate>2012-14-30T10:30:10Z</stopDate>
		<mms1>true</mms1>
		<mms2>false</mms2>
		<mms3>true</mms3>
		<mms4>false</mms4>
		<problem>bad_bias</problem>
		<description>THIS WILL FAIL VERIFICATION A minor test problem 3</description>
	</event>
</tables>
